/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        "outline-variant": "#c1c9ba",
        "primary-container": "#114f11",
        "on-surface-variant": "#41493e",
        "on-secondary-container": "#077323",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#2b4f2e",
        "on-primary-fixed": "#002201",
        primary: "#003703",
        "on-primary-container": "#81c175",
        "secondary-fixed": "#98f897",
        "on-primary-fixed-variant": "#155214",
        "inverse-surface": "#2d3133",
        tertiary: "#113518",
        "primary-fixed-dim": "#95d788",
        "on-secondary-fixed": "#002205",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#a8d1a7",
        "surface-variant": "#e0e3e5",
        outline: "#717a6c",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#005316",
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#7ddb7e",
        "on-tertiary-fixed": "#002107",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        error: "#ba1a1a",
        "inverse-primary": "#95d788",
        "on-tertiary": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-container": "#96f595",
        "surface-container-high": "#e6e8ea",
        surface: "#f7f9fb",
        secondary: "#006e20",
        "tertiary-container": "#284c2c",
        "on-tertiary-container": "#94bc93",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#c4edc2",
        "on-error": "#ffffff",
        "surface-tint": "#2f6b2a",
        "primary-fixed": "#b1f3a2",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
