import os
from pathlib import Path

import psycopg2


def load_env_file(env_path: Path) -> None:
    """Load KEY=VALUE pairs from a local .env file into os.environ."""
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


def get_connection():
    script_dir = Path(__file__).resolve().parent
    load_env_file(script_dir / ".env")

    return psycopg2.connect(
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        dbname=os.getenv("DB_NAME"),
    )


DDL_STATEMENTS = [
    # """
    # CREATE TABLE IF NOT EXISTS product_group (
    #     group_code VARCHAR(50) PRIMARY KEY,
    #     group_name VARCHAR(255) NOT NULL
    # );
    # """,
    """
    CREATE TABLE IF NOT EXISTS region (
        region_code VARCHAR(50) PRIMARY KEY,
        region_name VARCHAR(255) NOT NULL
    );
    """,
    # """
    # CREATE TABLE IF NOT EXISTS price_source (
    #     source_code VARCHAR(50) PRIMARY KEY,
    #     name VARCHAR(255) NOT NULL
    # );
    # """,
    # """
    # CREATE TABLE IF NOT EXISTS unit (
    #     unit_code VARCHAR(50) PRIMARY KEY,
    #     name VARCHAR(255) NOT NULL
    # );
    # """,
    # """
    # CREATE TABLE IF NOT EXISTS currency (
    #     currency_code VARCHAR(50) PRIMARY KEY,
    #     name VARCHAR(255) NOT NULL
    # );
    # """,
    """
    CREATE TABLE IF NOT EXISTS indicator (
        indicator_code VARCHAR(50) PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        category VARCHAR(100)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS stock_index_master (
        code VARCHAR(50) PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        market VARCHAR(100)
    );
    # """,
    # """
    # CREATE TABLE IF NOT EXISTS forecast_provider (
    #     forecast_provider_code VARCHAR(50) PRIMARY KEY,
    #     forecast_provider_name VARCHAR(255) NOT NULL
    # );
    # """,
    # """
    # CREATE TABLE IF NOT EXISTS price_latest (
    #     prod_code VARCHAR(50) PRIMARY KEY,
    #     price NUMERIC(18, 4),
    #     currency_code VARCHAR(50),
    #     last_updated_at TIMESTAMP,
    #     value_change NUMERIC(18, 4),
    #     percentage_change NUMERIC(5, 2),
    #     change_direction VARCHAR(20),
    #     CONSTRAINT fk_price_latest_product
    #         FOREIGN KEY (prod_code) REFERENCES product(prod_code),
    #     CONSTRAINT fk_price_latest_currency
    #         FOREIGN KEY (currency_code) REFERENCES currency(currency_code)
    # );
    # """,
    """
    CREATE TABLE IF NOT EXISTS indicator_data (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        indicator_code VARCHAR(50),
        region_code VARCHAR(50),
        value NUMERIC(18, 4),
        unit VARCHAR(50),
        period VARCHAR(50),
        period_type VARCHAR(50),
        created_at DATE,
        CONSTRAINT fk_indicator_data_indicator
            FOREIGN KEY (indicator_code) REFERENCES indicator(indicator_code),
        CONSTRAINT fk_indicator_data_region
            FOREIGN KEY (region_code) REFERENCES region(region_code)
    );
    """,
    # """
    # CREATE TABLE IF NOT EXISTS product (
    #     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    #     prod_code VARCHAR(50) UNIQUE NOT NULL,
    #     prod_name VARCHAR(255) NOT NULL,
    #     group_code VARCHAR(50),
    #     CONSTRAINT fk_product_group
    #         FOREIGN KEY (group_code) REFERENCES product_group(group_code)
    # );
    # """,
    """
    CREATE TABLE IF NOT EXISTS stock_index_price (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code VARCHAR(50),
        date DATE,
        close NUMERIC(18, 4),
        currency VARCHAR(50),
        CONSTRAINT fk_stock_index_price_master
            FOREIGN KEY (code) REFERENCES stock_index_master(code),
        CONSTRAINT fk_stock_index_price_currency
            FOREIGN KEY (currency) REFERENCES currency(currency_code)
    );
    """,
    # """
    # CREATE TABLE IF NOT EXISTS price_history (
    #     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    #     prod_code VARCHAR(50),
    #     price NUMERIC(18, 4),
    #     currency VARCHAR(50),
    #     unit VARCHAR(50),
    #     date DATE,
    #     source VARCHAR(50),
    #     CONSTRAINT fk_price_history_product
    #         FOREIGN KEY (prod_code) REFERENCES product(prod_code),
    #     CONSTRAINT fk_price_history_currency
    #         FOREIGN KEY (currency) REFERENCES currency(currency_code),
    #     CONSTRAINT fk_price_history_unit
    #         FOREIGN KEY (unit) REFERENCES unit(unit_code),
    #     CONSTRAINT fk_price_history_source
    #         FOREIGN KEY (source) REFERENCES price_source(source_code)
    # );
    # """,
    # """
    # CREATE TABLE IF NOT EXISTS price_forecast (
    #     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    #     prod_code VARCHAR(50),
    #     forecast_price NUMERIC(18, 4),
    #     currency VARCHAR(50),
    #     unit VARCHAR(50),
    #     forecast_period VARCHAR(50),
    #     forecast_provider VARCHAR(50),
    #     period_type VARCHAR(50),
    #     created_at DATE,
    #     CONSTRAINT fk_price_forecast_product
    #         FOREIGN KEY (prod_code) REFERENCES product(prod_code),
    #     CONSTRAINT fk_price_forecast_currency
    #         FOREIGN KEY (currency) REFERENCES currency(currency_code),
    #     CONSTRAINT fk_price_forecast_unit
    #         FOREIGN KEY (unit) REFERENCES unit(unit_code),
    #     CONSTRAINT fk_price_forecast_source
    #         FOREIGN KEY (forecast_provider) REFERENCES forecast_provider(forecast_provider_code)
    # );
    # """,
]


def create_tables():
    conn = get_connection()
    conn.autocommit = False

    try:
        with conn.cursor() as cur:
            for ddl in DDL_STATEMENTS:
                cur.execute(ddl)
        conn.commit()
        print("Tables created successfully.")
    except Exception as exc:
        conn.rollback()
        raise RuntimeError(f"Failed to create tables: {exc}") from exc
    finally:
        conn.close()


if __name__ == "__main__":
    create_tables()
